receivers:
    otlp:
        protocols:
            grpc:
exporters:
    otlp:
        endpoint: 0.0.0.0:4318
        tls:
            insecure: true
processors:
service:
    pipelines:
        traces:
            receivers: [otlp]
            processors: []
            exporters: [otlp]
